/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PmInsightsRouteImport } from './routes/pm-insights'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksSyncClaimsRouteImport } from './routes/api/public/hooks/sync-claims'
import { Route as ApiPublicHooksSyncAssetHistoryRouteImport } from './routes/api/public/hooks/sync-asset-history'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PmInsightsRoute = PmInsightsRouteImport.update({
  id: '/pm-insights',
  path: '/pm-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncClaimsRoute =
  ApiPublicHooksSyncClaimsRouteImport.update({
    id: '/api/public/hooks/sync-claims',
    path: '/api/public/hooks/sync-claims',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncAssetHistoryRoute =
  ApiPublicHooksSyncAssetHistoryRouteImport.update({
    id: '/api/public/hooks/sync-asset-history',
    path: '/api/public/hooks/sync-asset-history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/permissions': typeof PermissionsRoute
  '/pm-insights': typeof PmInsightsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/sync-asset-history': typeof ApiPublicHooksSyncAssetHistoryRoute
  '/api/public/hooks/sync-claims': typeof ApiPublicHooksSyncClaimsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/permissions': typeof PermissionsRoute
  '/pm-insights': typeof PmInsightsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/sync-asset-history': typeof ApiPublicHooksSyncAssetHistoryRoute
  '/api/public/hooks/sync-claims': typeof ApiPublicHooksSyncClaimsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/permissions': typeof PermissionsRoute
  '/pm-insights': typeof PmInsightsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/sync-asset-history': typeof ApiPublicHooksSyncAssetHistoryRoute
  '/api/public/hooks/sync-claims': typeof ApiPublicHooksSyncClaimsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claims'
    | '/login'
    | '/monitoring'
    | '/permissions'
    | '/pm-insights'
    | '/search'
    | '/settings'
    | '/api/public/hooks/sync-asset-history'
    | '/api/public/hooks/sync-claims'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claims'
    | '/login'
    | '/monitoring'
    | '/permissions'
    | '/pm-insights'
    | '/search'
    | '/settings'
    | '/api/public/hooks/sync-asset-history'
    | '/api/public/hooks/sync-claims'
  id:
    | '__root__'
    | '/'
    | '/claims'
    | '/login'
    | '/monitoring'
    | '/permissions'
    | '/pm-insights'
    | '/search'
    | '/settings'
    | '/api/public/hooks/sync-asset-history'
    | '/api/public/hooks/sync-claims'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimsRoute: typeof ClaimsRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  PermissionsRoute: typeof PermissionsRoute
  PmInsightsRoute: typeof PmInsightsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicHooksSyncAssetHistoryRoute: typeof ApiPublicHooksSyncAssetHistoryRoute
  ApiPublicHooksSyncClaimsRoute: typeof ApiPublicHooksSyncClaimsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm-insights': {
      id: '/pm-insights'
      path: '/pm-insights'
      fullPath: '/pm-insights'
      preLoaderRoute: typeof PmInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-claims': {
      id: '/api/public/hooks/sync-claims'
      path: '/api/public/hooks/sync-claims'
      fullPath: '/api/public/hooks/sync-claims'
      preLoaderRoute: typeof ApiPublicHooksSyncClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-asset-history': {
      id: '/api/public/hooks/sync-asset-history'
      path: '/api/public/hooks/sync-asset-history'
      fullPath: '/api/public/hooks/sync-asset-history'
      preLoaderRoute: typeof ApiPublicHooksSyncAssetHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimsRoute: ClaimsRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  PermissionsRoute: PermissionsRoute,
  PmInsightsRoute: PmInsightsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicHooksSyncAssetHistoryRoute: ApiPublicHooksSyncAssetHistoryRoute,
  ApiPublicHooksSyncClaimsRoute: ApiPublicHooksSyncClaimsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
